window.PLAYSTORE_LINKS={
"01-fashion-store-simulator-3d":"https://play.google.com/store/apps/details?id=com.supermarket.fashion.clothing.store.simulator",
"02-ludo-world":"https://play.google.com/store/apps/details?id=com.ludo.world.fun.dice.game",
"03-fashion-game":"https://play.google.com/store/apps/details?id=fashion.dressup.show.makeup.designer.style.battle",
"04-tattoo-games":"https://play.google.com/store/apps/details?id=com.biza.tattoogames.tattoo.design.studio.game",
"05-bubble-buster-2048":"https://play.google.com/store/apps/details?id=com.bubble.buster2048.ball.shooter.game",
"06-merge-the-number":"https://play.google.com/store/apps/details?id=com.merge.number.block.puzzle.games"
,
"07-art-asmr-tattoo":"https://play.google.com/store/apps/details?id=com.fc.hz.ink.art.tattoo.drawing.asmr",
"08-ball-sort":"https://play.google.com/store/apps/details?id=ball.sort.color.match.puzzle.games",
"09-car-sort-puzzle":"https://play.google.com/store/apps/details?id=com.parking.traffic.jam.car.games.sorting",
"10-dress-up-styles":"https://play.google.com/store/apps/details?id=com.biza.fashion.game.stylist.girl.games.dressup.gamesforgirls",
"11-find-the-difference":"https://play.google.com/store/apps/details?id=com.spot.hidden.difference.find.differences.puzzle.game",
"12-bubble-shooter-pop":"https://play.google.com/store/apps/details?id=com.popbubbles.bubbleshooter.classic.games",
"13-classic-sudoku-puzzle":"https://play.google.com/store/apps/details?id=sudoku.puzzle.free.brain.number.game",
"14-connect-the-dots":"https://play.google.com/store/apps/details?id=connect.dots.knot.pipeart.line.color.games",
"15-tic-tac-toe":"https://play.google.com/store/apps/details?id=com.TicTacToe.xoxo.board.puzzle.games",
"16-water-sort-puzzle":"https://play.google.com/store/apps/details?id=water.sort.color.puzzle.games.puzsort",
"17-find-the-difference-2":"https://play.google.com/store/apps/details?id=com.find.the.difference.spot.hidden.diff",
"find-the-difference":"https://play.google.com/store/apps/details?id=com.spot.hidden.difference.find.differences.puzzle.game",
"find-the-difference-02":"https://play.google.com/store/apps/details?id=com.find.the.difference.spot.hidden.diff",
"18-triple-match-goods":"https://play.google.com/store/apps/details?id=com.goodsmaster3d.triple.match.sort.puzzle"
};