# Scene list: (id, [(caption, tts_text_or_None)], min_duration)
SCENES = [
 ("night",   [("A bus depot after midnight.",None),
              ("Forty buses to charge, a grid limit you can't cross, and prices that move every hour.",None)], 8.0),
 ("operator",[("At two in the morning, the phone rings.",None),
              ("A charger said it was charging all night, and wasn't.",None),
              ("One bus won't leave the depot.",None),
              ("For years, that's how a depot was run: by reacting.",None)], 12.0),
 ("wheel",   [("enrouteQ runs the whole depot day, around the clock, on site.","en route Q runs the whole depot day, around the clock, on site."),
              ("It's an AI operator for the electric bus depot,",None),
              ("and in eQ Insight, you supervise instead of firefight.",None)], 11.0),
 ("insight", [("Before it ever touches a bus, Insight simulates your depot,",None),
              ("so you see it work, and what it saves, before anything goes live.",None),
              ("Nothing acts on a real charger until the simulation has earned it.",None)], 13.0),
 ("live",    [("Then the ring goes live.",None)], 3.2),
 ("connect", [("A bus pulls in, and eQ Connect already has it, on the map and down to the battery.",None)], 7.0),
 ("travel",  [("eQ Travel knows the journey it leaves for next.",None)], 4.0),
 ("optimiser",[("eQ Optimiser charges every bus for that departure at the cheapest hours of the night,",None),
              ("and re-orders the queue when the plan changes.",None)], 9.0),
 ("energy",  [("eQ Energy holds the site inside its grid limit.",None),
              ("At a real site, managed charging kept the peak at 3 kW instead of 166.","At a real site, managed charging kept the peak at three kilowatts, instead of a hundred and sixty-six."),
              ("A ninety-eight percent cut.",None),
              ("A bus depot's night runs the same way, in simulation at a real depot.",None)], 18.0),
 ("care",    [("When a charger says it's charging but nothing's flowing, eQ Care flags the bus before it's stranded.",None)], 7.0),
 ("hub",     [], 2.4),
 ("control", [("And if the connection drops, eQ Control keeps the site running safely offline.",None)], 5.0),
 ("forecast",[("Above the ring, eQ Forecast sees tomorrow before it arrives:",None),
              ("the peak, the price, and the buses at risk of leaving short.",None)], 9.0),
 ("benefit", [("Every day, you see what it was worth, settled per site.",None)], 5.0),
 ("valuate", [("And when a bus is finally sold, eQ Valuate puts a price on it.",None)], 6.0),
 ("bridge",  [("And next, eQ Bridge: a crew that speaks a dozen languages, each working in their own.",None),
              ("The driver says he's running late in Polish, and the manager reads it in Swedish.",None)], 12.0),
 ("close",   [("It proves itself in simulation, then runs your depot for real,",None),
              ("and after ninety days, we compare the two.",None),
              ("This runs in our depots today.",None),
              ("enrouteQ:","en route Q."),
              ("so the depot runs itself, and the two a.m. call doesn't come.","So the depot runs itself, and the two A M call doesn't come.")], 18.0),
]
